이름    :      그룬트와 함께 하는 노드제이에스

온:
     푸시    :
     가지        :      [ "주" ]
 pull_request :
     가지        :      [ "주" ]

직업:
     빌드    :
     런온        :      우분투 후기

     전략    :
     매트릭스    :
     노드버        :      [14.x,      16.x    ,      18.x    ]

     스텝    :
         -      사용    :      액션/체크아웃@v3

         -      이름   :     Node.js$를 사용하세요.{{      matrix.node-version      }}
    사용      :     동작/설정-노드@v3
    와   :
    노드버      :     ${{     matrix.node-version     }}

        -     이름   :     빌드
    실행      :     |
    npm설치    
   그루트   
